/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mcte;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.Timer;


/**
 *
 * @author DHRUV
 */

public class StudentView extends javax.swing.JFrame {
     NumberFormat format;
int score=0,count=0;
String path = System.getProperty("user.home") + "/Project4Files";
File qpaper=new File(path + "/qpaper.doc");
String ans="",time="";
BufferedReader br;
Timer timer;

int scores[];
int attempted[];
int optionselected[];

    /**
     * Creates new form StudentView
     */
    public StudentView(String name,String rollno) {
        
       
        initComponents();
        jLabel15.setVisible(false);
        jLabel10.setVisible(false);
        File timefile=new File(path + "/time.txt");
        try{
        BufferedReader brtime=new BufferedReader(new FileReader(timefile));
        time=brtime.readLine();
        brtime.close();
        }
        catch(Exception e){}
       
        
    
        jTextField1.setText(name);
        jTextField2.setText(rollno);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        try{
        BufferedReader brcount=new BufferedReader(new FileReader(qpaper));
        while(brcount.readLine()!=null){
        count++;
        brcount.readLine();
        brcount.readLine();
        brcount.readLine();
        brcount.readLine();
        brcount.readLine();
        }
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }
        format = NumberFormat.getNumberInstance();
    format.setMinimumIntegerDigits(2);
         int timecount=Integer.parseInt(time) *60000;
       // timerlabel.setText(String.valueOf(timecount));
       TimeClass tc=new TimeClass(timecount);
        timer =new Timer(1000,tc);
        timer.start();
        
        try {        
        br=new BufferedReader(new FileReader(qpaper));
        jTextArea1.setText(br.readLine());
        jRadioButton1.setText(br.readLine());
        jRadioButton2.setText(br.readLine());
        jRadioButton3.setText(br.readLine());
        jRadioButton4.setText(br.readLine());
        ans=br.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }
        optionselected=new int[count];
        scores=new int[count];
        for(int i=0;i<count;i++)
        {
        scores[i]=0;
        optionselected[i]=0;
        }
        attempted=new int[count];
        for(int i=0;i<count;i++)
        {
        attempted[i]=0;
        }
    }
    public class TimeClass implements ActionListener {
   int counter;
   
   public TimeClass(int counter)
   {
    this.counter=counter; 
   }
   public void actionPerformed(ActionEvent tc){
        counter=counter-1000;
   if(counter >=1){
     
    int minutes = (int)(counter/60000);
    
    int seconds = (int)((counter)/1000);
    if(seconds>=60)
        seconds=seconds-60;
    timerlabel.setText(format.format(minutes) + ":" + format.format(seconds));
   //timerlabel.setText(String.valueOf(counter));
    
   }
   else
   {
   timer.stop();
   jLabel15.setVisible(true);
   jPanel2.setVisible(false);
   //timerlabel.setVisible(false);
   //jLabel9.setVisible(false);
   
   
    
   Toolkit.getDefaultToolkit().beep();
   
   }
  
   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelqno = new javax.swing.JLabel();
        jLabelqanswered = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelq1 = new javax.swing.JLabel();
        jLabelq2 = new javax.swing.JLabel();
        jLabelq3 = new javax.swing.JLabel();
        jLabelq4 = new javax.swing.JLabel();
        jLabelq5 = new javax.swing.JLabel();
        jLabelq6 = new javax.swing.JLabel();
        jLabelq7 = new javax.swing.JLabel();
        jLabelq8 = new javax.swing.JLabel();
        jLabelq9 = new javax.swing.JLabel();
        jLabelq10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        timerlabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelcontainer = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        popupMenu1.setLabel("popupMenu1");

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelqno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelqno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelqno.setText("1");
        jPanel1.add(jLabelqno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 20, -1));

        jLabelqanswered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelqanswered.setForeground(new java.awt.Color(0, 0, 255));
        jLabelqanswered.setText("0");
        jPanel1.add(jLabelqanswered, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 20, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/question.jpg"))); // NOI18N
        jLabel2.setText("23");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 920, 40));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 720, 80));

        jRadioButton1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/submit.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 140, 50));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("ROLL NO.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jTextField2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jTextField2.setOpaque(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 150, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/endtest.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 230, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 180, 30));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 180, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/previousnext.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 930, 30));

        jLabel10.setBackground(new java.awt.Color(0, 255, 102));
        jLabel10.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel10.setText("ATTEMPTED");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, 20));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        jLabelq1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq1.setText("Q1");
        jLabelq1.setOpaque(true);
        jLabelq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, 30));

        jLabelq2.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq2.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq2.setText("Q2");
        jLabelq2.setOpaque(true);
        jLabelq2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 50, 30));

        jLabelq3.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq3.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq3.setText("Q3");
        jLabelq3.setOpaque(true);
        jLabelq3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 50, 30));

        jLabelq4.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq4.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq4.setText("Q4");
        jLabelq4.setOpaque(true);
        jLabelq4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 50, 30));

        jLabelq5.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq5.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq5.setText("Q5");
        jLabelq5.setOpaque(true);
        jLabelq5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 50, 30));

        jLabelq6.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq6.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq6.setText("Q6");
        jLabelq6.setOpaque(true);
        jLabelq6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 50, 30));

        jLabelq7.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq7.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq7.setText("Q7");
        jLabelq7.setOpaque(true);
        jLabelq7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 50, 30));

        jLabelq8.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq8.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq8.setText("Q8");
        jLabelq8.setOpaque(true);
        jLabelq8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 304, 50, 30));

        jLabelq9.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabelq9.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq9.setText("Q9");
        jLabelq9.setOpaque(true);
        jLabelq9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, 50, 30));

        jLabelq10.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabelq10.setForeground(new java.awt.Color(255, 0, 51));
        jLabelq10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelq10.setText("Q10");
        jLabelq10.setOpaque(true);
        jLabelq10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelq10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabelq10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 50, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/qno.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 50, 500));

        jLabel14.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("GO TO:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 4, -1, 20));

        jLabel15.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TIME OVER");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 180, 30));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timerlabel.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        timerlabel.setForeground(new java.awt.Color(51, 255, 51));
        timerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(timerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("MINUTES");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/clock2.jpg"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 170, 130));

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel8.setText("TIME LEFT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, 30));

        jLabelcontainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcte/mcq2.jpg"))); // NOI18N
        jPanel1.add(jLabelcontainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Toolkit.getDefaultToolkit().beep();
        String name,rollno;
       name=jTextField1.getText();
       rollno=jTextField2.getText(); 
       if(jLabel15.isVisible())
       { 
       int sum=0;
       JOptionPane.showMessageDialog(null," TIME OVER");
       for(int i=0;i<count;i++)
       {
       //JOptionPane.showMessageDialog(null,"score : "+scores[i]);
       sum+=scores[i];
       }
        this.setVisible(false);
           
        Final s=new Final(name,rollno,sum,count);
        s.setVisible(true);
        this.dispose();
        return;
      }
        if(!jRadioButton1.isSelected() &&!jRadioButton2.isSelected()&& !jRadioButton3.isSelected() && !jRadioButton4.isSelected()) 
     { JOptionPane.showMessageDialog(null,"Select some option");
       return;
     }   
    
     
     attempted[Integer.parseInt(jLabelqno.getText())-1]=1;
     if(jLabel10.isVisible())
     {
         scores[Integer.parseInt(jLabelqno.getText())-1]=0;
     }
  /*   
     if(jRadioButton5.isSelected()){
        
         scores[Integer.parseInt(jLabelqno.getText())-1]=0;
         
     }*/
     
     if(jRadioButton1.isSelected())
       {
         if(jRadioButton1.getText().equals(ans)){
             scores[Integer.parseInt(jLabelqno.getText())-1]=1;
             
         }
         optionselected[Integer.parseInt(jLabelqno.getText())-1]=1;
       }
       if(jRadioButton2.isSelected())
       {
         if(jRadioButton2.getText().equals(ans)){
             scores[Integer.parseInt(jLabelqno.getText())-1]=1;
             
         }
         optionselected[Integer.parseInt(jLabelqno.getText())-1]=2;
       }
       if(jRadioButton3.isSelected())
       {
         if(jRadioButton3.getText().equals(ans)){
             scores[Integer.parseInt(jLabelqno.getText())-1]=1;
             
         }
         optionselected[Integer.parseInt(jLabelqno.getText())-1]=3;
       }
       if(jRadioButton4.isSelected())
       {
         if(jRadioButton4.getText().equals(ans)){
             scores[Integer.parseInt(jLabelqno.getText())-1]=1;
             
         }
         optionselected[Integer.parseInt(jLabelqno.getText())-1]=4;
       }
      
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);   
       
      
       String qno=jLabelqno.getText();
       if(!(jLabel10.isVisible()))
       {
       jLabelqanswered.setText(String.valueOf(Integer.parseInt(jLabelqanswered.getText())+1));
       }
       
       /*if(!(jRadioButton5.isSelected()))
       jLabelqanswered.setText(String.valueOf(Integer.parseInt(jLabelqanswered.getText())+1));
       
       */
       
       int qnum=Integer.parseInt(jLabelqno.getText());
       if(qnum==1)
       {
          
       jLabelq1.setBackground(Color.GREEN);
       }
       if(qnum==2)
       {
       jLabelq2.setBackground(Color.GREEN);
       }
       if(qnum==3)
       {
       jLabelq3.setBackground(Color.GREEN);
       }
       if(qnum==4)
       {
       jLabelq4.setBackground(Color.GREEN);
       }
       if(qnum==5)
       {
       jLabelq5.setBackground(Color.GREEN);
       }
       if(qnum==6)
       {
       jLabelq6.setBackground(Color.GREEN);
       }
       if(qnum==7)
       {
       jLabelq7.setBackground(Color.GREEN);
       }
       if(qnum==8)
       {
       jLabelq8.setBackground(Color.GREEN);
       }
       if(qnum==9)
       {
       jLabelq9.setBackground(Color.GREEN);
       }
       if(qnum==10)
       {
       jLabelq10.setBackground(Color.GREEN);
       }
       if(Integer.parseInt(jLabelqno.getText())==count){
       JOptionPane.showMessageDialog(null,"no more questions \n");
       return;
        }
     
     
        try {        
        BufferedReader br=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<=Integer.parseInt(qno);i++)
        {
        br.readLine();
        br.readLine();
        br.readLine();
        br.readLine();
        br.readLine();
        br.readLine();
        }
        
        
        jTextArea1.setText(br.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br.readLine());
        jRadioButton2.setText(br.readLine());
        jRadioButton3.setText(br.readLine());
        jRadioButton4.setText(br.readLine());
        ans=br.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }
        jLabelqno.setText(String.valueOf(Integer.parseInt(jLabelqno.getText())+1));
         qno=jLabelqno.getText();
        int option=optionselected[Integer.parseInt(qno)-1];
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        jLabel10.setVisible(true);
       // jRadioButton5.setSelected(true);
        }
        else
        {
//        jRadioButton5.setSelected(false);
        jLabel10.setVisible(false);
        }
       
        
      // if(!(jRadioButton5.isSelected()))
       //jLabelqanswered.setText(String.valueOf(Integer.parseInt(jLabelqanswered.getText())+1));
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      if(jRadioButton1.isSelected()){
       jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);      
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
      if(jRadioButton2.isSelected()){
       jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);      
      }   // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
       if(jRadioButton3.isSelected()){
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       jRadioButton4.setSelected(false);      
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
      if(jRadioButton4.isSelected()){
       jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);      
      }   // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String name,rollno;
       name=jTextField1.getText();
       rollno=jTextField2.getText();
        int sum=0;
       for(int i=0;i<count;i++)
       {
       sum+=scores[i];
       }
       int dialogResult = JOptionPane.showConfirmDialog (null, "Would you really like to end test and get final score ?");
       
if(dialogResult == JOptionPane.YES_OPTION){
    
       //JOptionPane.showMessageDialog(null,"Your final score is :  " +sum);
    try {
        Student.addStudent(rollno,name,sum);// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setVisible(false);
     Final f=new Final(name,rollno,sum,count);
            f.setVisible(true);
            this.dispose();
      }
 else
    return;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
  //String name=jTextField1.getText();
       String attempqno,prevscore;
        String name,rollno;
       name=jTextField1.getText();
       rollno=jTextField2.getText(); 
       if(jLabel15.isVisible())
       { 
       int sum=0;
       JOptionPane.showMessageDialog(null," TIME OVER");
       for(int i=0;i<count;i++)
       {
       //JOptionPane.showMessageDialog(null,"score : "+scores[i]);
       sum+=scores[i];
       }
        this.setVisible(false);
           
        Final s=new Final(name,rollno,sum,count);
        s.setVisible(true);
        this.dispose();
        return;
      } 
      
       if(Integer.parseInt(jLabelqno.getText())>1){
       jLabelqno.setText(String.valueOf(Integer.parseInt(jLabelqno.getText())-1));
       }
        String qno=jLabelqno.getText();
        int option=optionselected[Integer.parseInt(qno)-1];
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        jLabel10.setVisible(true);
//        jRadioButton5.setSelected(true);
        }
        else
        {
     //   jRadioButton5.setSelected(false);
        jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br3=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<Integer.parseInt(qno);i++)
        {
        br3.readLine();
        br3.readLine();
        br3.readLine();
        br3.readLine();
        br3.readLine();
        br3.readLine();
        }
        
        
        jTextArea1.setText(br3.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br3.readLine());
        jRadioButton2.setText(br3.readLine());
        jRadioButton3.setText(br3.readLine());
        jRadioButton4.setText(br3.readLine());
        ans=br3.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }
                  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
  //String name=jTextField1.getText();
  
    String name,rollno;
       name=jTextField1.getText();
       rollno=jTextField2.getText(); 
       if(jLabel15.isVisible())
       { 
       int sum=0;
       JOptionPane.showMessageDialog(null," TIME OVER");
       for(int i=0;i<count;i++)
       {
       //JOptionPane.showMessageDialog(null,"score : "+scores[i]);
       sum+=scores[i];
       }
        this.setVisible(false);
           
        Final s=new Final(name,rollno,sum,count);
        s.setVisible(true);
        this.dispose();
        return;
      } 
       if(Integer.parseInt(jLabelqno.getText())==count)
       {
        JOptionPane.showMessageDialog(null,"no more questions");
       return;
       }
       jLabelqno.setText(String.valueOf(Integer.parseInt(jLabelqno.getText())+1));
       
        
        String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<Integer.parseInt(qno);i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabelq1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq1MouseClicked
jLabelqno.setText("1");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<1;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq1MouseClicked

    private void jLabelq2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq2MouseClicked
jLabelqno.setText("2");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<2;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq2MouseClicked

    private void jLabelq3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq3MouseClicked
jLabelqno.setText("3");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<3;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq3MouseClicked

    private void jLabelq4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq4MouseClicked
jLabelqno.setText("4");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<4;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq4MouseClicked

    private void jLabelq5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq5MouseClicked
jLabelqno.setText("5");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<5;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq5MouseClicked

    private void jLabelq6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq6MouseClicked
jLabelqno.setText("6");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<6;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq6MouseClicked

    private void jLabelq7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq7MouseClicked
jLabelqno.setText("7");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<7;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq7MouseClicked

    private void jLabelq8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq8MouseClicked
jLabelqno.setText("8");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<8;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq8MouseClicked

    private void jLabelq9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq9MouseClicked
jLabelqno.setText("9");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<9;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq9MouseClicked

    private void jLabelq10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelq10MouseClicked
jLabelqno.setText("10");
String qno=jLabelqno.getText();
         int option=optionselected[Integer.parseInt(qno)-1];
         if(option==0)
        {
        jRadioButton1.setSelected(false);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
       //JOptionPane.showMessageDialog(null,option +"in question no ."+ qno);
        if(option==1)
        {
        jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==2)
        {
        jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==3)
        {
        jRadioButton3.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton1.setSelected(false);
       jRadioButton4.setSelected(false);
        }
        if(option==4)
        {
        jRadioButton4.setSelected(true);
         jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton1.setSelected(false);
        }
        if(attempted[Integer.parseInt(qno)-1]==1){
        
//        jRadioButton5.setSelected(true);
        jLabel10.setVisible(true);
        }
        else{
           // jRadioButton5.setSelected(false);
           jLabel10.setVisible(false);
        }
        try {        
       BufferedReader br2=new BufferedReader(new FileReader(qpaper));
        for(int i=1;i<10;i++)
        {
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        br2.readLine();
        }
        
        
        jTextArea1.setText(br2.readLine());
        jTextArea1.setEditable(false);
        jRadioButton1.setText(br2.readLine());
        jRadioButton2.setText(br2.readLine());
        jRadioButton3.setText(br2.readLine());
        jRadioButton4.setText(br2.readLine());
        ans=br2.readLine();
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelq10MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelcontainer;
    private javax.swing.JLabel jLabelq1;
    private javax.swing.JLabel jLabelq10;
    private javax.swing.JLabel jLabelq2;
    private javax.swing.JLabel jLabelq3;
    private javax.swing.JLabel jLabelq4;
    private javax.swing.JLabel jLabelq5;
    private javax.swing.JLabel jLabelq6;
    private javax.swing.JLabel jLabelq7;
    private javax.swing.JLabel jLabelq8;
    private javax.swing.JLabel jLabelq9;
    private javax.swing.JLabel jLabelqanswered;
    private javax.swing.JLabel jLabelqno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel timerlabel;
    // End of variables declaration//GEN-END:variables
}
