/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videostore;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DHRUV
 */
public class CustView2 extends javax.swing.JFrame {
String path = System.getProperty("user.home") + "/Project5Files";
int daysgap=0; 
 Date dcurrent=new Date();
 double n;
 int purchasecount=0;

 String pattern = "dd-MM-yyyy";
 // String pattern = "dd-MM-yyyy";
      String mydate =new SimpleDateFormat(pattern).format(dcurrent);
   // String[] data=new String[4];
    
    DefaultTableModel model;
    String[] data=new String[5];
    ArrayList<Store> s=new ArrayList<Store>();
    ArrayList<CustPurchase> c=new ArrayList<CustPurchase>();
    /**
     * Creates new form CustView2
     */
    public CustView2(String Custno) {
         initComponents();
          model=(DefaultTableModel)jTable1.getModel();  
        //  String[] data=new String[5];
    data[0]="";
    data[1]="";
    data[2]="";
    data[3]="";     
     data[4]="";
    //Date dcurrent=new Date();

 
      jLabel7.setText(mydate);
      
       jTextField6.setText(Custno);
        try{    FileInputStream fis = new FileInputStream(path + "/store.ser");
ObjectInputStream ois = new ObjectInputStream(fis);
s = (ArrayList<Store>) ois.readObject();
ois.close();
      }
      
      catch(Exception e){
   e.printStackTrace();
      }   
       int i,c1=0,c2=0,c3=0,c4=0,c5=0;
       for(i=0;i<s.size();i++)
       {
       if(s.get(i).type.equals("MP4 CD") && s.get(i).isavail.equals("yes"))
           c1++;
       if(s.get(i).type.equals("VHS CD") && s.get(i).isavail.equals("yes"))
           c2++;
       if(s.get(i).type.equals("MP4 DVD") && s.get(i).isavail.equals("yes"))
           c3++;
       if(s.get(i).type.equals("VHS DVD") && s.get(i).isavail.equals("yes"))
           c4++;
       if(s.get(i).type.equals("MUSIC CD") && s.get(i).isavail.equals("yes"))
           c5++;
       }
       jTextField1.setText(String.valueOf(c1));
       jTextField2.setText(String.valueOf(c2));
       jTextField3.setText(String.valueOf(c3));
       jTextField4.setText(String.valueOf(c4));
       jTextField5.setText(String.valueOf(c5));
         try{    FileInputStream fis = new FileInputStream(path + "/"+Custno+".ser");
ObjectInputStream ois = new ObjectInputStream(fis);
c= (ArrayList<CustPurchase>) ois.readObject();
ois.close();
      }
      
      catch(Exception e){
       //e.printStackTrace();
       //JOptionPane.showMessageDialog(null,e);
      }
         //SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
       for( i=0;i<c.size();i++)
             {
             data[0]=c.get(i).type;
             data[1]=c.get(i).procdate;
             data[2]=c.get(i).prize;
             data[3]=c.get(i).rent;
             data[4]=c.get(i).date;
             //JOptionPane.showMessageDialog(null,data[0] + data[1] + data[2]+  data[3]);
            model.addRow(data);
            
           
         }
       
       
       
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        button1 = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        button4 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        button5 = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1050, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Video  available:");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, 30));

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton1.setText("CD MP4");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton2.setText("CD VHS");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton3.setText("DVD MP4");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText(" AVAILABILITY");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 30));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 50, 30));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 30));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, 30));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 40, 30));

        jRadioButton5.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton5.setText("MUSIC CD");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 50, 30));

        jRadioButton4.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton4.setText("DVD VHS");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        button1.setLabel("BUY");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 70, 30));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("MUSIC");
        jLabel11.setOpaque(true);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 20, 70, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("AVAILABILITY");
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 110, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 810, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videostore/custview.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 480));

        jTabbedPane1.addTab("TAKE ITEM", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TYPE", "DATE OF PROCUREMENT", "PRIZE", "DAILY RENTAL CHARGE", "DATE OF PURCHASE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setFocusable(false);
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 680, 390));

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel8.setText("Enter the item No. You Want to Return:");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 340, 30));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 40, 30));

        button4.setLabel("RETURN ITEM");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel2.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videostore/cust2.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 490));

        jTabbedPane1.addTab("RETURN ITEM", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button5.setLabel("CANCEL MEMBERSHIP");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel3.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videostore/custview.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 490));

        jTabbedPane1.addTab("CANCEL MEMBERSHIP", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, -1, 514));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setEditable(false);
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 131, -1));

        button2.setLabel("LOG OUT");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel4.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        button3.setLabel("REFRESH");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel4.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CUSTOMER'S NUMBER:");
        jLabel5.setOpaque(true);
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 160, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel3.setText("DATE:");
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videostore/head.jpg"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1055, 77));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);

        } // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if(jRadioButton3.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(false);
            jRadioButton4.setSelected(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if(jRadioButton4.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton1.setSelected(false);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
      this.setVisible(false);
      Home h=new Home();
      h.setVisible(true);
      this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       purchasecount++;
       if(purchasecount!=1)
       {
       JOptionPane.showMessageDialog(null,"cannot buy more, 1st logout");
       return;
       }
        String custno,line,count;
        try{    FileInputStream fis = new FileInputStream(path + "/store.ser");
ObjectInputStream ois = new ObjectInputStream(fis);
s = (ArrayList<Store>) ois.readObject();
ois.close();
      }
      
      catch(Exception e){
       
      }
        custno=jTextField6.getText();
        CustPurchase item1=new CustPurchase();
        CustPurchase item2=new CustPurchase();
        int i;
        item1.type="";
        item2.type="";
        item1.date=mydate;
        item2.date=mydate;
        if(jRadioButton1.isSelected())
        { 
          jTextField1.setText(String.valueOf(Integer.parseInt(String.valueOf(jTextField1.getText()))-1));
          item1.type="MP4 CD";
          SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          for( i=0;i<s.size();i++)
          {
           if(s.get(i).type.equals("MP4 CD") && s.get(i).isavail.equals("yes"))
           {    
                item1.procdate=s.get(i).date;
                item1.prize=s.get(i).prize;
                item1.rent=s.get(i).rent;
                 try{
        Date d = formatter.parse(s.get(i).date);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        if(daysgap>=365){
        n=daysgap/365;
         
      item1.rent=String.valueOf(Integer.parseInt(item1.rent)/Math.pow(2,n));
     
        }
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
                break;
           }
          }
          
          s.get(i).isavail="no";
             try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
          c.add(item1);
           try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
           
 }
         if(jRadioButton2.isSelected())
        {jTextField2.setText(String.valueOf(Integer.parseInt(String.valueOf(jTextField2.getText()))-1));
          item1.type="VHS CD";
          SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          for( i=0;i<s.size();i++)
          {
           if(s.get(i).type.equals("VHS CD")&& s.get(i).isavail.equals("yes"))
           {    item1.procdate=s.get(i).date;
                item1.prize=s.get(i).prize;
                item1.rent=s.get(i).rent;
                 try{
        Date d = formatter.parse(item1.procdate);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        if(daysgap>=365){
        n=daysgap/365;
         
      item1.rent=String.valueOf(Integer.parseInt(item1.rent)/Math.pow(2,n));
     
        }
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
                break;
           }
          }
          
          s.get(i).isavail="no";
             try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
          c.add(item1);
           try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
           
        }
       if(jRadioButton3.isSelected())
        {jTextField3.setText(String.valueOf(Integer.parseInt(String.valueOf(jTextField3.getText()))-1));
          item1.type="MP4 DVD";
          SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          for( i=0;i<s.size();i++)
          {
           if(s.get(i).type.equals("MP4 DVD")&& s.get(i).isavail.equals("yes"))
           {    item1.procdate=s.get(i).date;
                item1.prize=s.get(i).prize;
                item1.rent=s.get(i).rent;
                 try{
        Date d = formatter.parse(item1.procdate);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        if(daysgap>=365){
        n=daysgap/365;
         
      item1.rent=String.valueOf(Integer.parseInt(item1.rent)/Math.pow(2,n));
     
        }
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
                break;
           }
          }
          
          s.get(i).isavail="no";
             try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
          c.add(item1);
           try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
           
        } 
         if(jRadioButton4.isSelected())
        {jTextField4.setText(String.valueOf(Integer.parseInt(String.valueOf(jTextField4.getText()))-1));
          item1.type="VHS DVD";
          SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          for( i=0;i<s.size();i++)
          {
           if(s.get(i).type.equals("VHS DVD")&& s.get(i).isavail.equals("yes"))
           {    item1.procdate=s.get(i).date;
                item1.prize=s.get(i).prize;
                item1.rent=s.get(i).rent;
                 try{
        Date d = formatter.parse(item1.procdate);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        if(daysgap>=365){
        n=daysgap/365;
         
      item1.rent=String.valueOf(Integer.parseInt(item1.rent)/Math.pow(2,n));
     
        }
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
                break;
           }
          }
          
          s.get(i).isavail="no";
             try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
          c.add(item1);
           try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
           
        }
       if(jRadioButton5.isSelected())

       {  jTextField5.setText(String.valueOf(Integer.parseInt(String.valueOf(jTextField5.getText()))-1));
          item2.type="MUSIC CD";
          SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          for( i=0;i<s.size();i++)
          {
           if(s.get(i).type.equals("MUSIC CD")&& s.get(i).isavail.equals("yes"))
           {    item2.procdate=s.get(i).date;
                item2.prize=s.get(i).prize;
                item2.rent=s.get(i).rent;
                 try{
        Date d = formatter.parse(item2.procdate);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        if(daysgap>=365){
        n=daysgap/365;
         
      item2.rent=String.valueOf(Integer.parseInt(item2.rent)/Math.pow(2,n));
     
        }
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
                break;
           }
          }
          
          s.get(i).isavail="no";
             try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
          c.add(item2);
           try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
           
 }
       rent r=new rent(custno,item1,item2);
       //this.setVisible(false);
       r.setVisible(true);
       
       // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
     String itemno;
     String custno=jTextField6.getText();
     itemno=jTextField7.getText();
     if(Integer.parseInt(itemno)>jTable1.getRowCount())
     {   JOptionPane.showMessageDialog(null,"enter correct number");
         return;
     }
     if(model.getRowCount()==0)
      
    
     {JOptionPane.showMessageDialog(null, "no item to return");
         return;
     }
     CustPurchase cust=new CustPurchase();
     Store st=new Store();
     
     st.type=cust.type=data[0]=(String)model.getValueAt(Integer.parseInt(itemno)-1,0);
     st.date=cust.procdate=data[1]=(String)model.getValueAt(Integer.parseInt(itemno)-1,1);
     st.prize=cust.prize=data[2]=(String)model.getValueAt(Integer.parseInt(itemno)-1,2);
     st.rent=cust.rent=data[3]=(String)model.getValueAt(Integer.parseInt(itemno)-1,3);
     data[4]=cust.date=(String)model.getValueAt(Integer.parseInt(itemno)-1,4);
     st.isavail="no";
     //JOptionPane.showMessageDialog(null,"type=" + st.type+ "date=" +st.date+ "prize= "+ st.prize+"rent="+st.rent);
     int i;
     for(i=0;i<c.size();i++)
      {
          if(c.get(i).type.equals(cust.type) && c.get(i).date.equals(cust.date) && c.get(i).rent.equals(cust.rent)&& c.get(i).prize.equals(cust.prize) )
          {
           //JOptionPane.showMessageDialog(null,"Object found");
           break;
          }
      }
     if(i<c.size())
     c.remove(i);
      try{  
FileOutputStream fos = new FileOutputStream(path + "/"+custno+".ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(c);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }  
       int size=s.size();
      
      for(i=0;i<size;i++)
      {
          if(s.get(i).type.equals(st.type) && s.get(i).date.equals(st.date) && s.get(i).rent.equals(st.rent)&& s.get(i).prize.equals(st.prize) && s.get(i).isavail.equals(st.isavail))
          {
           //JOptionPane.showMessageDialog(null,"Object found");
           break;
          }
      }
    //  JOptionPane.showMessageDialog(null,i);
      if(i<s.size())
      s.get(i).isavail="yes";
      
      try{  
FileOutputStream fos = new FileOutputStream(path + "/store.ser");
ObjectOutputStream oos = new ObjectOutputStream(fos);
oos.writeObject(s);
oos.close();
  }
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }
      
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
          
         try {
        Date d = formatter.parse(data[4]);
        daysgap=(int)( (dcurrent.getTime() - d.getTime()) / (1000 * 60 * 60 * 24));
        
        
        
    } catch (ParseException ex) {
        Logger.getLogger(ManagerView.class.getName()).log(Level.SEVERE, null, ex);
    }  
        
    double amount=Double.parseDouble(data[3])*daysgap;
      
      
     model.removeRow(Integer.parseInt(itemno)-1);
   
     Amount a=new Amount(amount,custno,data[0]);
    a.setVisible(true);
    
     // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
       this.setVisible(false);
       CustView2 c=new CustView2(jTextField6.getText());
       c.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
  if(model.getRowCount()>0)
  {
  JOptionPane.showMessageDialog(null,"You have dues left out against you");
  return;
  }
  else
  {
   File f=new File(path + "/"+jTextField6.getText()+".ser");
   f.delete();
   JOptionPane.showMessageDialog(null,"Your membership has been cancelled you can take your 1000rs");
   Home h=new Home();
   this.setVisible(false);
   h.setVisible(true);
   this.dispose();
  }// TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
