
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.lang.reflect.Array;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 /**
 *
 * @author DHRUV
 */
public class Home extends javax.swing.JFrame {
       Socket s;
      
        OutputStream os ;
        ObjectOutputStream dos; 
        InputStream is;
        ObjectInputStream ois;
        Work[] w;
        Diary diary=new Diary("7302");
      
      GregorianCalendar cal=new GregorianCalendar();
      int date=cal.get(Calendar.DAY_OF_MONTH);
      int month=cal.get(Calendar.MONTH)+1;
      int year=cal.get(Calendar.YEAR);
      List<String> inpuexec=new ArrayList<String>();
      List<String> execid=new ArrayList<String>();
      ArrayList<String> names  = new ArrayList<String>();
      /**
     * Creates new form Home
     */
    public Home(String[] info) throws IOException {
        initComponents();
        jLabel74.setText(String.valueOf(date));
        jTextField1.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);
        jTextField14.setEditable(false);
        jTextField4.setEditable(false);
        jTextField9.setEditable(false);
        jTextArea1.setEditable(false);
        
        jLabel6.setText(String.valueOf(date)+"-"+String.valueOf(month)+"-"+String.valueOf(year));
        jLabel3.setText(info[0]);
        jLabel15.setText(info[0]);
        jLabel16.setText(info[3]);
        jLabel17.setText(info[1]);
        jLabel33.setText(info[4]);
        jLabel22.setText(info[5]);
       
        String hostname = "10.102.70.39";
        int port = 12345;
        try{
            
        s = new Socket(hostname,port);  
        os = s.getOutputStream();  
        dos = new ObjectOutputStream(os);  
        is=s.getInputStream();
        ois=new ObjectInputStream(is);
        
        dos.writeObject("2");
        dos.writeObject(info[1]);
       
   
        List<String> diarylist = new ArrayList<String>();   
        diarylist=(ArrayList<String>)ois.readObject();
        inpuexec=(ArrayList<String>)ois.readObject();
        String msg=(String)ois.readObject();
        System.out.println(msg);
        jTextArea1.setText(msg);
        diary=arraytodiary(diarylist);
       
        w=diary.getsingleDaytimetable(date);
        if(w[0]!=null)
        jLabel76.setText(w[0].getName());
        if(w[1]!=null)
        jLabel77.setText(w[1].getName());
        if(w[2]!=null)
        jLabel78.setText(w[2].getName());
        if(w[3]!=null)
        jLabel79.setText(w[3].getName());
        if(w[4]!=null)
        jLabel80.setText(w[4].getName());
        
        
        for (String element : diarylist) {
        System.out.println(element);
        }
    
        }
        catch(Exception e){
        e.printStackTrace();
        }
        
        
        for(int i=0;i<inpuexec.size();i=i+2){
        
        names.add(inpuexec.get(i+1));
        }    
        String[] exec= new String[names.size()];
            
        names.toArray(exec);
            
        jList2.setListData(exec);
        jList2.setSelectionModel(new MySelectionModel(jList2,10));
        
  
    }
      
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabelworkpurpose = new javax.swing.JLabel();
        jLabelpurpose = new javax.swing.JLabel();
        jLabelvenue = new javax.swing.JLabel();
        jLabelname = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel82 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel88 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel89 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel90 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel86 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1319, 779));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(300, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("TODAY'S TIMETABLE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel76.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel76MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel76MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel76MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel76MousePressed(evt);
            }
        });
        jPanel2.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 250, 60));

        jLabel77.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel77MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel77MouseExited(evt);
            }
        });
        jPanel2.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 240, 60));

        jLabel78.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabel78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel78MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel78MouseExited(evt);
            }
        });
        jPanel2.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 240, 60));

        jLabel79.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabel79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel79MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel79MouseExited(evt);
            }
        });
        jPanel2.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 240, 60));

        jLabel80.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabel80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel80MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel80MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel80MouseExited(evt);
            }
        });
        jPanel2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 240, 60));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Times.jpg"))); // NOI18N
        jPanel2.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 455, 300));

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel84.setText("DETAILS");
        jPanel2.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));
        jPanel2.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 170, 20));

        jLabelworkpurpose.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabelworkpurpose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelworkpurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, 20));

        jLabelpurpose.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabelpurpose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelpurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, 20));

        jLabelvenue.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabelvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 210, 20));

        jLabelname.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
        jLabelname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 190, 20));

        jLabel85.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stick.jpg"))); // NOI18N
        jPanel2.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schedule2.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jTabbedPane1.addTab("VIEW SCHEDULE", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 14, 100, 110));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel10.setText("NAME:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel11.setText("ADDRESS:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel12.setText("EMPLOYEE ID.:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 20));

        jLabel16.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 350, 30));

        jLabel17.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 350, 30));

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel13.setText("NO. OF MEETING PLANNED THIS MONTH: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel18.setText(" LEAVES AVAILED:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel22.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel22.setText(" ");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 80, 30));

        jLabel33.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 70, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.jpg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        jTabbedPane1.addTab("VIEW PROFILE", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("1");
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 70, 40));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 60, 40));

        jLabel44.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("3");
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 70, 40));

        jLabel45.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("4");
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 70, 40));

        jLabel46.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("5");
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 70, 40));

        jLabel47.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("6");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 70, 40));

        jLabel48.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("7");
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 70, 40));

        jLabel49.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("8");
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 70, 40));

        jLabel50.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("9");
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 80, 40));

        jLabel51.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("10");
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 70, 40));

        jLabel52.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("11");
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 80, 40));

        jLabel53.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("12");
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 70, 40));

        jLabel54.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("13");
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 70, 40));

        jLabel55.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("14");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 70, 40));

        jLabel56.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("15");
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 70, 40));

        jLabel57.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("16");
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, 40));

        jLabel58.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("17");
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 70, 40));

        jLabel59.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("18");
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 80, 40));

        jLabel60.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("19");
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 70, 40));

        jLabel61.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("20");
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 80, 40));

        jLabel62.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("21");
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 70, 50));

        jLabel63.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("22");
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 70, 40));

        jLabel64.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("23");
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 40));

        jLabel65.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("24");
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 40));

        jLabel66.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("25");
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 80, 40));

        jLabel67.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("26");
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel67MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 70, 40));

        jLabel68.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("27");
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel68MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 80, 40));

        jLabel69.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("28");
        jLabel69.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel69MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 70, 40));

        jLabel70.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("29");
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 40));

        jLabel71.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("30");
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel71MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 70, 40));

        jLabel72.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("31");
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 70, 40));

        jLabel42.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calender2.jpg"))); // NOI18N
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 580, 360));

        jLabel74.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 40, 50));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Calendar-icon.png"))); // NOI18N
        jPanel4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 100, 90));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatediarywall.jpg"))); // NOI18N
        jPanel4.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jTabbedPane1.addTab("UPDATE & VIEW DIARY", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel20.setText("SELECT NAME OF EXECUTIVES");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel21.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel21.setText("DATE OF MEETING");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel23.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel23.setText("VENUE OF MEETING");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel24.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel24.setText("PROJECT OF MEETING");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sales", "Customer_Review", "Presentation", "Development" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 200, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel5.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 30));

        jScrollPane2.setViewportView(jList2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 130, 150));

        jLabel82.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel82.setText("NUMBER OF EXECUTIVES");
        jPanel5.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jTextField1.setText(" ");
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 30));

        jScrollPane1.setViewportView(jList1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 120, 150));

        jButton1.setText(" DONE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V1", "V2", "V3", "V4" }));
        jPanel5.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, 30));

        jLabel88.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel88MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 60, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meeting4.jpg"))); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        jTabbedPane1.addTab("REGISTER APPOINTMENT", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 255));
        jLabel26.setText("TAKE LEAVE");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 170, 40));

        jLabel27.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel27.setText("PURPOSE");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, 30));

        jLabel28.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel28.setText("DAY IN MONTH");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 220, 30));
        jPanel6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel6.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, 30));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok.jpg"))); // NOI18N
        jLabel89.setText("jLabel89");
        jLabel89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel89MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 60, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.jpg"))); // NOI18N
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));

        jTabbedPane1.addTab("PLAN LEAVE", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("DATE:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("TIME");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 60, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("SLOT");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("PURPOSE");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));
        jPanel7.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 190, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9am to 10 am", "10 am to 11 am", "11 am to 12 noon", "1 pm to 2 pm", "2 pm to 3 pm" }));
        jPanel7.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 120, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel7.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 60, 30));

        jLabel90.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel90MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 70, 50));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job2.jpg"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));

        jTabbedPane1.addTab("PLAN IMPORTANT JOB", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel36.setText("SELECT PERIOD:");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, 20));

        jLabel37.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel37.setText("FROM:");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel38.setText("TO:");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("TOTAL WORKING HOURS");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("TIME SPENT ON MEETINGS");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("FRACTION OF TIME SPENT ON MEETINGS");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 70, 30));
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 70, 30));
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 70, 30));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 30));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel8.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel8.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meeting3.jpg"))); // NOI18N
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        jTabbedPane1.addTab("TIME SPENT ON MEETINGS", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 590, 190));

        jLabel86.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 0, 0));
        jLabel86.setText("MESSAGE");
        jPanel9.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 130, 20));

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inbox2.jpg"))); // NOI18N
        jLabel83.setText("jLabel83");
        jPanel9.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jTabbedPane1.addTab("INBOX", jPanel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1320, 700));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("WELCOME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 260, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("DATE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 180, 20));

        jLabel87.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel87MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brown234.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private static class MySelectionModel extends DefaultListSelectionModel
{
    private JList list;
    private int maxCount;

    private MySelectionModel(JList list,int maxCount)
    {
        this.list = list;

        this.maxCount = maxCount;
    }

    @Override
    public void setSelectionInterval(int index0, int index1)
    {
        if (index1 - index0 >= maxCount)
        {
            index1 = index0 + maxCount - 1;
        }
        super.setSelectionInterval(index0, index1);
    }

    @Override
    public void addSelectionInterval(int index0, int index1)
    {
        int selectionLength = list.getSelectedIndices().length;
        if (selectionLength >= maxCount)
            return;

        if (index1 - index0 >= maxCount - selectionLength)
        {
            index1 = index0 + maxCount - 1 - selectionLength;
        }
        if (index1 < index0)
            return;
        super.addSelectionInterval(index0, index1);
    }
}
    public Diary arraytodiary(List<String> list){
    String exid=list.get(0);
        Month m=new Month(Integer.parseInt(list.get(1)),Integer.parseInt(list.get(2)));
        int index=4;
        Map<Integer,Day> timetable;
        timetable = new HashMap<>();
        for(int i=1;i<=m.getdays();i++,index++){
            Work[] work=new Work[5];
            Date date = new Date(m.getyear(), m.getmonthint(), i);
            
            for(int k=0;k<5;k++){
                String type = list.get(index);
                switch(type){
                    case "OPENSLOT":
                        work[k]=null;
                        index++;
                        break;
                    case "IMPORTANT JOB":
                        work[k]=new Job(date, list.get(index+1), new Slot(k), exid);
                        index+=2;
                        break;
                    case "LEAVE":
                        work[k]=new Leave(date, exid, list.get(index+1));
                        index+=2;
                        break;
                    case "MEETING":
                        String pur=list.get(index+1);
                        String ven=list.get(index+2);
                        String caller=list.get(index+3);
                        int no_of_ex=Integer.parseInt(list.get(index+4));
                        if(no_of_ex==0){
                        work[k]=new Meeting(pur, ven, new Slot(k), date);
                        index+=5;
                        }
                        else {
                        String[] str= new String[no_of_ex];
                        for(int j=0;j<no_of_ex;j++){
                        str[j]=list.get(index+5+j);
                        }
                        work[k]=new Meeting(caller, date, str, ven, pur);
                        index+=(5+no_of_ex);
                        }
                        
                }
            }
            Day day=new Day(i, date.getDayint(), work);
            timetable.put(i, day);
        }
        Diary dnew=new Diary(exid, m, timetable);
        return dnew;
    
    }
    public List<String> diarytoarray(Diary d)
    {
        List<String> list = new ArrayList<String>();
        list.add(d.getexecuitve_id());
        list.add(String.valueOf(d.getmonth().getmonthint()));
        list.add(String.valueOf(d.getmonth().getyear()));
        Work[] w=new Work[5];
        
        for(int k=1;k<=d.getmonth().getdays();k++){
        list.add(String.valueOf(k));
        w=d.getsingleDaytimetable(k);
        for(int i=0;i<5;i++){
        if(w[i]==null){
        list.add("OPENSLOT");
        }
        else
        {
        list.add(w[i].getName());
        
        if(w[i].getName().equals("MEETING"))
        {
         list.add(w[i].getpurpose());
         Meeting m = (Meeting)w[i];
         list.add(m.getvenue());
         if(m.getcallerexecutive_id()==null)
             list.add("null");
         else list.add(m.getcallerexecutive_id());
         list.add(String.valueOf(m.getnumberofexecutives()));
         for(int j=0;j<m.getnumberofexecutives();j++){
         list.add(m.getExecutiveID(j));
         }
        }
        if(w[i].getName().equals("IMPORTANT JOB"))
        {
         list.add(w[i].getpurpose());
        }
        if(w[i].getName().equals("LEAVE"))
        {
        list.add(w[i].getpurpose());
        }
      }
    }
 }
        return list;
    }
    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
   int date=Integer.parseInt(jLabel43.getText());
   
   daydiary d=new daydiary( date,month,year,diary,s,dos,ois);
   d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
int date=Integer.parseInt(jLabel14.getText());
   
   daydiary d=new daydiary( date,month,year,diary,s,dos,ois);
   d.setVisible(true);      
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel76MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseEntered
        if(w[0]==null)
        jLabelname.setText("OPENSLOT");
        else
        {
            jLabelname.setText(w[0].getName());
        if(w[0].getName().equals("MEETING"))
        {
         jLabelpurpose.setText(w[0].getpurpose());
         Meeting m = (Meeting)w[0];
        
         jLabelvenue.setText(m.getvenue());
        }
        
        if(w[0].getName().equals("IMPORTANT JOB") || w[0].getName().equals("LEAVE")){
           jLabelworkpurpose.setText(w[0].getpurpose());
        }
        }
    
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel76MouseEntered

    private void jLabel76MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseExited
       jLabelname.setText("");
       
jLabel81.setText("");
jLabelworkpurpose.setText("");
jLabelpurpose.setText("");
jLabelvenue.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jLabel76MouseExited

    private void jLabel76MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel76MousePressed

    private void jLabel76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel76MouseClicked

    private void jLabel77MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseEntered
 if(w[1]==null)
        jLabelname.setText("OPENSLOT");
        else
        {
            jLabelname.setText(w[1].getName());
        if(w[1].getName().equals("MEETING"))
        {
         jLabelpurpose.setText(w[1].getpurpose());
         Meeting m = (Meeting)w[1];
        
         jLabelvenue.setText(m.getvenue());
        }
        
        if(w[1].getName().equals("IMPORTANT JOB") || w[1].getName().equals("LEAVE")){
           jLabelworkpurpose.setText(w[1].getpurpose());
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel77MouseEntered

    private void jLabel78MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseEntered
 if(w[2]==null)
        jLabelname.setText("OPENSLOT");
        else
        {
            jLabelname.setText(w[2].getName());
        if(w[2].getName().equals("MEETING"))
        {
         jLabelpurpose.setText(w[2].getpurpose());
         Meeting m = (Meeting)w[2];
        
         jLabelvenue.setText(m.getvenue());
        }
        
        if(w[2].getName().equals("IMPORTANT JOB") || w[2].getName().equals("LEAVE")){
           jLabelworkpurpose.setText(w[2].getpurpose());
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel78MouseEntered

    private void jLabel79MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel79MouseEntered
 if(w[3]==null)
        jLabelname.setText("OPENSLOT");
        else
        {
            jLabelname.setText(w[3].getName());
        if(w[3].getName().equals("MEETING"))
        {
         jLabelpurpose.setText(w[3].getpurpose());
         Meeting m = (Meeting)w[3];
        
         jLabelvenue.setText(m.getvenue());
        }
        
        if(w[3].getName().equals("IMPORTANT JOB") || w[3].getName().equals("LEAVE")){
           jLabelworkpurpose.setText(w[3].getpurpose());
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel79MouseEntered

    private void jLabel80MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel80MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel80MouseClicked

    private void jLabel80MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel80MouseEntered
 if(w[4]==null)
        jLabelname.setText("OPENSLOT");
        else
        {
            jLabelname.setText(w[4].getName());
        if(w[4].getName().equals("MEETING"))
        {
         jLabelpurpose.setText(w[4].getpurpose());
         Meeting m = (Meeting)w[4];
        
         jLabelvenue.setText(m.getvenue());
        }
        
        if(w[4].getName().equals("IMPORTANT JOB") || w[4].getName().equals("LEAVE")){
           jLabelworkpurpose.setText(w[4].getpurpose());
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel80MouseEntered

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
int date=Integer.parseInt(jLabel44.getText());
  
   daydiary d=new daydiary( date,month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
int date=Integer.parseInt(jLabel45.getText());
  
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
int date=Integer.parseInt(jLabel46.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
int date=Integer.parseInt(jLabel47.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
int date=Integer.parseInt(jLabel48.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
int date=Integer.parseInt(jLabel49.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
int date=Integer.parseInt(jLabel50.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
int date=Integer.parseInt(jLabel51.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
int date=Integer.parseInt(jLabel52.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
int date=Integer.parseInt(jLabel53.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
int date=Integer.parseInt(jLabel54.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
int date=Integer.parseInt(jLabel55.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
int date=Integer.parseInt(jLabel56.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
int date=Integer.parseInt(jLabel57.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
int date=Integer.parseInt(jLabel58.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
int date=Integer.parseInt(jLabel59.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
int date=Integer.parseInt(jLabel60.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
int date=Integer.parseInt(jLabel61.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
int date=Integer.parseInt(jLabel62.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
int date=Integer.parseInt(jLabel63.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
int date=Integer.parseInt(jLabel64.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
int date=Integer.parseInt(jLabel65.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
int date=Integer.parseInt(jLabel66.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseClicked
int date=Integer.parseInt(jLabel67.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel67MouseClicked

    private void jLabel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseClicked
int date=Integer.parseInt(jLabel68.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel68MouseClicked

    private void jLabel69MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel69MouseClicked
int date=Integer.parseInt(jLabel69.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel69MouseClicked

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
int date=Integer.parseInt(jLabel70.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel70MouseClicked

    private void jLabel71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseClicked
int date=Integer.parseInt(jLabel71.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel71MouseClicked

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
int date=Integer.parseInt(jLabel72.getText());
   
   
   daydiary d=new daydiary( date, month,year,diary,s,dos,ois);
   d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel72MouseClicked

    private void jLabel77MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseExited
 jLabelname.setText("");
       
jLabel81.setText("");
jLabelworkpurpose.setText("");
jLabelpurpose.setText("");
jLabelvenue.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel77MouseExited

    private void jLabel78MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseExited
 jLabelname.setText("");
       
jLabel81.setText("");
jLabelworkpurpose.setText("");
jLabelpurpose.setText("");
jLabelvenue.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel78MouseExited

    private void jLabel79MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel79MouseExited
 jLabelname.setText("");
       
jLabel81.setText("");
jLabelworkpurpose.setText("");
jLabelpurpose.setText("");
jLabelvenue.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel79MouseExited

    private void jLabel80MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel80MouseExited
 jLabelname.setText("");
       
jLabel81.setText("");
jLabelworkpurpose.setText("");
jLabelpurpose.setText("");
jLabelvenue.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel80MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            jList1.setListData(jList2.getSelectedValues());
            jTextField1.setText(String.valueOf(jList1.getModel().getSize()));
            Object[] values=jList2.getSelectedValues();
            String[] execname = new String[values.length];
            int count=0;
            for(Object o:values){
              execname[count]=(String)o;
              count++;
            } 
            int j=0;
            for(int i=1;i<inpuexec.size();i=i+2){
                for(j=0;j<values.length;j++){
                if( inpuexec.get(i).equals(execname[j])){
                    execid.add(inpuexec.get(i-1));
                }
                }
                
            }
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
          
          
            //TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int d1,d2;
       d1=Integer.parseInt((String)jComboBox7.getSelectedItem());
       d2=Integer.parseInt((String)jComboBox8.getSelectedItem());
       List<String> l=new ArrayList<>();
       if(d1>d2)
       { JOptionPane.showMessageDialog(null,"Enter valid details");
         return;
       }
       else{
           try{
         dos.writeObject("8");
         l.add(jLabel17.getText());
         l.add(String.valueOf(d1));
         l.add(String.valueOf(d2));
         dos.writeObject(l);
         String s1=(String)ois.readObject();
         String s2=(String)ois.readObject();
         jTextField13.setText(s1);
         jTextField12.setText(s2);
         System.out.println(s1+"ans"+s2);
         int wh,mh;
         wh=Integer.parseInt(jTextField12.getText());
         mh=Integer.parseInt(jTextField13.getText());
         float fraction=(float)mh/wh;
         jTextField14.setText(String.valueOf(fraction));
         
             }
           
          catch(Exception e){e.printStackTrace();}
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel87MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel87MouseClicked
  try{
        dos.writeObject("5");
       dos.close();
       s.close();
       welcome w=new welcome();
       this.setVisible(false);
       this.dispose();
       w.setVisible(true);
       
       }
catch(Exception e){
e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel87MouseClicked

    private void jLabel88MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel88MouseClicked
 List<String> meeting=new ArrayList<String>();
        if(Integer.parseInt((String)jComboBox5.getSelectedItem())<date){
         JOptionPane.showMessageDialog(rootPane,"Enter correct date");
         return;
        }
        meeting.add(jLabel17.getText());
        meeting.add((String)jComboBox5.getSelectedItem());
        meeting.add(String.valueOf(month-1));
        meeting.add(String.valueOf(year));
        meeting.add(jTextField1.getText());
        for(int i=0;i<execid.size();i++){
        meeting.add(execid.get(i));
        }
        
        meeting.add((String)jComboBox6.getSelectedItem());
        meeting.add((String)jComboBox1.getSelectedItem());
       
        try{
           dos.writeObject("4");
           dos.writeObject(meeting);
        }catch(Exception e){
        e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel88MouseClicked

    private void jLabel89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel89MouseClicked
        String d=(String)jComboBox3.getSelectedItem();
        int date=Integer.parseInt(d);
        if(date<this.date)
        {
        JOptionPane.showMessageDialog(rootPane,"Enter correct Date");
        
        }
        int check=diary.takeNewLeave(date,jTextField4.getText());
        List<String> diarylist = new ArrayList<String>();
        diarylist=diarytoarray(diary);
           try {
               dos.writeObject("3");
               dos.writeObject(diarylist);
           } catch (IOException ex) {
               Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
           }
        
        
        
        //0 means rescheduled day has a MEETING, 1 means it already has a leave, 2 means success
        if(check==0){
        JOptionPane.showMessageDialog(rootPane,"Rescheduled day has meeting");
        }
        if(check==1)
        {
        JOptionPane.showMessageDialog(rootPane,"Rescheduled day is already a leave");
        }
        if(check==2)
        {
        JOptionPane.showMessageDialog(rootPane,"Leave availed !!!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel89MouseClicked

    private void jLabel90MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel90MouseClicked
  int dayinmonth=Integer.parseInt((String)jComboBox4.getSelectedItem());
       if(dayinmonth<this.date)
       {
       JOptionPane.showMessageDialog(rootPane,"Enter correct Date");
       }
       int slot=jComboBox2.getSelectedIndex();
       String purpose=jTextField9.getText();
       int check=diary.planNewJob(purpose,dayinmonth, slot);
        List<String> diarylist = new ArrayList<String>();
        diarylist=diarytoarray(diary);
           try {
               dos.writeObject("3");
               dos.writeObject(diarylist);
           } catch (IOException ex) {
               Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
           }
                 //0 day has Leave
		//1 day and slot has Meeting
		//2 day and slot has already a Job
		//3 success
       if(check==0){
       JOptionPane.showMessageDialog(rootPane, "Day has Leave, can't Plan job");
       return;
       }
       if(check==1){
       JOptionPane.showMessageDialog(rootPane, "Day and slot has meeting, so cant plan job");
       return;
       }
       if(check==2){
       JOptionPane.showMessageDialog(rootPane,"Day and slot has JOB");
       return;
       }
       if(check==3){
       JOptionPane.showMessageDialog(rootPane,"Job Successfully planned");
       return;
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel90MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelpurpose;
    private javax.swing.JLabel jLabelvenue;
    private javax.swing.JLabel jLabelworkpurpose;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
