/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.market;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author DHRUV
 */
public class Prize extends javax.swing.JFrame {
String path = System.getProperty("user.home") + "/Project1Files";
    /**
     * Creates new form Prize
     */
    public Prize() {
        initComponents();
           File f = new File(path + "/NoOfCust.txt");
     int Custcount=0;
     try{ BufferedReader br = new BufferedReader(new FileReader(f));
          Custcount = Integer.parseInt(br.readLine());
          br.close();
     }
     catch(Exception e)
     {
      JOptionPane.showMessageDialog(null,e);
      
     }
     int i,max;
     max=0;
     String custno="",purchase="",maxcn="",maxadd="";
     File fmax = new File(path + "/C20141" +".txt");
      try{BufferedReader bmax = new BufferedReader(new FileReader(fmax));
      purchase=bmax.readLine();
      max=Integer.parseInt(purchase);
      maxcn="C20141";
      bmax.close();
      }
      catch(Exception e)
      {
      JOptionPane.showMessageDialog(null,e);
      }
      File fmax2 = new File(path + "/C20141" +"details"+".txt");
      try{BufferedReader bmax2 = new BufferedReader(new FileReader(fmax2));
      maxadd=bmax2.readLine();
      bmax2.close();
      }
      catch(Exception e)
      {
      JOptionPane.showMessageDialog(null,e);
      }
    
     for(i=1;i<=Custcount;i++)
     {
      custno="C2014"+i;
     File f2 = new File(path + "/" + custno + ".txt");
     File f3 = new File(path + "/" + custno +"details"+ ".txt");
     try{ BufferedReader br = new BufferedReader(new FileReader(f2));
         BufferedReader br2 = new BufferedReader(new FileReader(f3));
         String address=br2.readLine();
        purchase = br.readLine();
        if(Integer.parseInt(purchase)>max)
        {
            max=Integer.parseInt(purchase);
            maxcn=custno;
            maxadd=address;
        }
        if(Integer.parseInt(purchase)>10000)
        {
        jTextArea2.append(custno+":"+address+"\n");
           
        }
        br.close();
        br2.close();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e);
     }
     }
     jLabelwinner.setText(maxcn+":"+maxadd);
     jTextArea2.setEditable(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelwinner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabelwinner)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelwinner)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SURPRISE GIFT WINNER", jPanel1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("GOLD COIN WINNERS", jPanel2);

        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       my.market.marketUI fram=new my.market.marketUI();
       fram.setVisible(true);
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prize().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelwinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
